import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import AuthProvider from '@/auth/Provider'

const myFont = localFont({
  src: './Minecraftia.woff',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
