import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.scss'
import AuthProvider from '@/auth/Provider'
import { ConfigProvider } from 'antd'

const myFont = localFont({
  src: './Minecraftia.woff',
  display: 'swap',
  variable: '--font',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <ConfigProvider
          theme={{
            token: {
              fontFamily: myFont.style.fontFamily,
              borderRadius: 0,
            },
          }}
        >
          <AuthProvider>{children}</AuthProvider>
        </ConfigProvider>
      </body>
    </html>
  )
}
